apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: sec-headers
  namespace: gv
spec:
  headers:
    frameDeny: true
    browserXssFilter: true
    contentTypeNosniff: true
    sslRedirect: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true