service:
  type: LoadBalancer

ports:
  web:
    port: 80
  websecure:
    port: 443

additionalArguments:
  - --providers.kubernetescrd
  - --entrypoints.web.address=:80
  - --entrypoints.web.http.redirections.entrypoint.to=websecure
  - --entrypoints.web.http.redirections.entrypoint.scheme=https
  - --entrypoints.websecure.address=:443
  - --certificatesresolvers.letsencrypt.acme.email=js@asappz.com
  - --certificatesresolvers.letsencrypt.acme.storage=/data/acme.json
  - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web

persistence:
  enabled: true
  size: 128Mi
